 version: 2

 jobs:
   build:
     executor: win/default   
     steps:
     - checkout
     - run:
         name: Restore
         command:
            dotnet restore
         working_directory: SlimFormaturas.Api
     - run:
         name: Build
         command:
            dotnet build -c Release
         working_directory: SlimFormaturas.Api
