version: 2.1
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run:
           name: Build
           command: |
              docker build .
       - run:
           name: public on heroku
           command: |
              docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
              heroku container:push web -app $APP_NAME
              heroku container:release web -app $APP_NAME
