version: 2
jobs:
   build:
     docker:
       - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
     steps:
       - checkout
       - run:
           name: Test Docker
           command: |
              docker --version
              docker info
