// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlimFormaturas.Infra.Data.Context;

namespace SlimFormaturas.Infra.Data.Migrations
{
    [DbContext(typeof(MssqlContext))]
    [Migration("20190925021954_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SlimFormaturas.Domain.Entities.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Cep");

                    b.Property<string>("City");

                    b.Property<string>("Complement");

                    b.Property<string>("GraduateId");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("Number");

                    b.Property<string>("Street");

                    b.Property<string>("Uf");

                    b.HasKey("AddressId");

                    b.HasIndex("GraduateId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("SlimFormaturas.Domain.Entities.Graduate", b =>
                {
                    b.Property<string>("GraduateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Agency");

                    b.Property<string>("Bank");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("CheckingAccount");

                    b.Property<bool>("Committee");

                    b.Property<string>("Cpf");

                    b.Property<string>("DadName");

                    b.Property<DateTime>("DateRegister");

                    b.Property<string>("Email");

                    b.Property<string>("MotherName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Photo");

                    b.Property<string>("Rg");

                    b.Property<bool>("Sex");

                    b.HasKey("GraduateId");

                    b.ToTable("Graduate");
                });

            modelBuilder.Entity("SlimFormaturas.Domain.Entities.Phone", b =>
                {
                    b.Property<string>("PhoneId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ddd");

                    b.Property<string>("GraduateId");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("PhoneId");

                    b.HasIndex("GraduateId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("SlimFormaturas.Domain.Entities.Address", b =>
                {
                    b.HasOne("SlimFormaturas.Domain.Entities.Graduate", "Graduate")
                        .WithMany("Address")
                        .HasForeignKey("GraduateId");
                });

            modelBuilder.Entity("SlimFormaturas.Domain.Entities.Phone", b =>
                {
                    b.HasOne("SlimFormaturas.Domain.Entities.Graduate", "Graduate")
                        .WithMany("Phone")
                        .HasForeignKey("GraduateId");
                });
#pragma warning restore 612, 618
        }
    }
}
